apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taskplatform
data:
  NODE_ENV: "production"
  PORT: "4000"
  JWT_EXPIRES_IN: "900"
  REFRESH_TOKEN_EXPIRES_IN: "604800"
  LOG_LEVEL: "info"
  CORS_ORIGINS: "https://taskplatform.dev"
  FROM_EMAIL: "noreply@taskplatform.dev"
