apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: taskplatform
type: Opaque
stringData:
  DATABASE_URL: "postgresql://taskuser:taskpass@postgres-service:5432/taskdb"
  REDIS_URL: "redis://redis-service:6379"
  JWT_SECRET: "change-me-in-production-min-32-chars!!"
  SMTP_HOST: ""
  SMTP_PORT: "587"
  SMTP_USER: ""
  SMTP_PASS: ""
